server:
    port: ${PORT:9000}
spring:
  application:
      name: ignite-intro
  profiles:
      active: local

logging:
  level:
     ROOT: INFO
     com.alexkbit.intro: DEBUG
     org.springframework: INFO

app.ignite:
  cluster.addresses: 127.0.0.1:47500..47509
  persistent:
    active: false
    path: /persistent

---
spring:
  profiles: local

---
spring:
  profiles: test

---
spring:
  profiles: cluster-test

---
spring:
  profiles: dev

app.ignite:
  persistent.active: true
